collections:
  sites:
    output: false
  pages:
    output: true
    permalink: /:name/

jekyll-minifier:
  exclude: "game/*"

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - bin/
  - *.nix
  - result
